/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2133c372-2d5b-44cd-a63f-6395ab51b015",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ufEXUfDdA",
    "aws_user_pools_web_client_id": "1m0e9n34iv657q4uq996m46l6a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://36vgqxzfpfgbdlxwhgfosowjky.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
